#!/bin/bash
set -x
DIR=certs
rm -r $DIR
mkdir $DIR
pushd $DIR
openssl genrsa -aes128 2048 >server.key
openssl rsa -in server.key -out server.key 
openssl req -utf8 -new -key server.key -out server.csr 
openssl x509 -in server.csr -out server.crt -req -signkey server.key -days 3650 
chmod 600 server.key 
popd
oc create secret tls jws-app-secret --cert=certs/server.crt --key=certs/server.key